
services:
  core-api-service:
    build: ./backend/core-api-service
    container_name: core-api
    ports:
      - "3001:3001"
    volumes:
      #- ./backend/core-api-service/data:/app/data 
      - sqlite_data:/app/data
      # Optional: Map scripts so you can edit python without rebuilding
      - ./backend/core-api-service/scripts:/app/scripts
      # Hot-reload: Map the source code so you don't have to rebuild on every change
      - ./backend/core-api-service:/app
      # IGNORE node_modules: Use the container's installed modules, not your local ones
      - /app/node_modules
    environment:
      - DB_PATH=/app/data/app.db
      - NODE_ENV=development

  timescaledb:
    image: timescale/timescaledb:latest-pg17
    container_name: timescaledb
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password 
      - POSTGRES_DB=orderflow_db
    ports:
      - "5432:5432"
    volumes:
      - timescale_data:/var/lib/postgresql/data
      #- ./backend/timescaledb_data:/var/lib/postgresql/data

  orderflow-engine-service:
    build: ./backend/orderflow-engine-service 
    container_name: orderflow_engine
    depends_on:
      - timescaledb # wait for db to start
    volumes:
      - ./backend/orderflow-engine-service:/app
    environment:
      - DB_HOST=timescaledb # Docker Hostname
      - DB_PORT=5432
      - DB_USER=admin
      - DB_PASS=password
      - DB_NAME=orderflow_db

# SQLite Viewer (Web Interface)
  sqlite-web:
    image: coleifer/sqlite-web
    ports:
      - "8080:8080"
    volumes:
      - sqlite_data:/data 
    command: sqlite_web -H 0.0.0.0 -p 8080 /data/app.db

volumes:
  sqlite_data:
  timescale_data: